defmodule AutomatedAgency.Repo.Migrations.MakeKeywordUniqueForTopicAnalysis do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:keywords, [:keyword, :topic_analysis_id],
             name: "keywords_unique_keyword_index"
           )
  end

  def down do
    drop_if_exists unique_index(:keywords, [:keyword, :topic_analysis_id],
                     name: "keywords_unique_keyword_index"
                   )
  end
end
