defmodule AutomatedAgency.Repo.Migrations.UpdateScreenshotDataToBeBinary do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute(
      "ALTER TABLE screenshots ALTER COLUMN mobile_data TYPE bytea USING mobile_data::bytea"
    )

    execute(
      "ALTER TABLE screenshots ALTER COLUMN desktop_data TYPE bytea USING desktop_data::bytea"
    )
  end

  def down do
    alter table(:screenshots) do
      modify :desktop_data, :text
      modify :mobile_data, :text
    end
  end
end
