defmodule AutomatedAgency.Repo.Migrations.MakeUxCriticismUniqueForUxAnalysis do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:ux_criticisms, [:criticism, :ux_analysis_id],
             name: "ux_criticisms_unique_criticism_index"
           )
  end

  def down do
    drop_if_exists unique_index(:ux_criticisms, [:criticism, :ux_analysis_id],
                     name: "ux_criticisms_unique_criticism_index"
                   )
  end
end
