defmodule AutomatedAgency.Repo.Migrations.AddScreenshotResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:screenshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :desktop_data, :text
      add :mobile_data, :text

      add :page_id,
          references(:pages,
            column: :id,
            name: "screenshots_page_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:screenshots, "screenshots_page_id_fkey")

    drop table(:screenshots)
  end
end
