defmodule AutomatedAgency.Repo.Migrations.SetupUniquenessForHasOneRelationToPage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:ux_analyses, [:page_id], name: "ux_analyses_unique_on_page_index")

    create unique_index(:topic_analyses, [:page_id], name: "topic_analyses_unique_on_page_index")

    create unique_index(:speed_analyses, [:page_id], name: "speed_analyses_unique_on_page_index")

    create unique_index(:screenshots, [:page_id], name: "screenshots_unique_on_page_index")

    create unique_index(:improved_pages, [:page_id], name: "improved_pages_unique_on_page_index")
  end

  def down do
    drop_if_exists unique_index(:improved_pages, [:page_id],
                     name: "improved_pages_unique_on_page_index"
                   )

    drop_if_exists unique_index(:screenshots, [:page_id],
                     name: "screenshots_unique_on_page_index"
                   )

    drop_if_exists unique_index(:speed_analyses, [:page_id],
                     name: "speed_analyses_unique_on_page_index"
                   )

    drop_if_exists unique_index(:topic_analyses, [:page_id],
                     name: "topic_analyses_unique_on_page_index"
                   )

    drop_if_exists unique_index(:ux_analyses, [:page_id],
                     name: "ux_analyses_unique_on_page_index"
                   )
  end
end
