defmodule AutomatedAgency.Repo.Migrations.DisallowNilForAllExistingAttributesInDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ux_criticisms) do
      modify :ux_analysis_id, :uuid, null: false
      modify :explanation, :text, null: false
      modify :criticism, :text, null: false
      modify :severity, :text, null: false
    end

    alter table(:ux_analyses) do
      modify :page_id, :uuid, null: false
    end

    alter table(:topic_analyses) do
      modify :page_id, :uuid, null: false
      modify :primary_category, :text, null: false
    end

    alter table(:speed_analyses) do
      modify :page_id, :uuid, null: false
      modify :mobile_data, :map, null: false
      modify :desktop_data, :map, null: false
    end

    alter table(:screenshots) do
      modify :page_id, :uuid, null: false
      modify :mobile_data, :text, null: false
      modify :desktop_data, :text, null: false
    end

    alter table(:pages) do
      modify :domain_id, :uuid, null: false
      modify :html, :text, null: false
      modify :url, :text, null: false
    end

    alter table(:keywords) do
      modify :topic_analysis_id, :uuid, null: false
      modify :keyword, :text, null: false
    end

    alter table(:improved_pages) do
      modify :page_id, :uuid, null: false
      modify :html, :text, null: false
    end

    alter table(:domains) do
      modify :domain, :text, null: false
    end
  end

  def down do
    alter table(:domains) do
      modify :domain, :text, null: true
    end

    alter table(:improved_pages) do
      modify :html, :text, null: true
      modify :page_id, :uuid, null: true
    end

    alter table(:keywords) do
      modify :keyword, :text, null: true
      modify :topic_analysis_id, :uuid, null: true
    end

    alter table(:pages) do
      modify :url, :text, null: true
      modify :html, :text, null: true
      modify :domain_id, :uuid, null: true
    end

    alter table(:screenshots) do
      modify :desktop_data, :text, null: true
      modify :mobile_data, :text, null: true
      modify :page_id, :uuid, null: true
    end

    alter table(:speed_analyses) do
      modify :desktop_data, :map, null: true
      modify :mobile_data, :map, null: true
      modify :page_id, :uuid, null: true
    end

    alter table(:topic_analyses) do
      modify :primary_category, :text, null: true
      modify :page_id, :uuid, null: true
    end

    alter table(:ux_analyses) do
      modify :page_id, :uuid, null: true
    end

    alter table(:ux_criticisms) do
      modify :severity, :text, null: true
      modify :criticism, :text, null: true
      modify :explanation, :text, null: true
      modify :ux_analysis_id, :uuid, null: true
    end
  end
end
