// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AnalysisDomainImport } from './routes/analysis/$domain'
import { Route as AnalysisPagePageIdImport } from './routes/analysis/page/$pageId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AnalysisDomainRoute = AnalysisDomainImport.update({
  path: '/analysis/$domain',
  getParentRoute: () => rootRoute,
} as any)

const AnalysisPagePageIdRoute = AnalysisPagePageIdImport.update({
  path: '/analysis/page/$pageId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/analysis/$domain': {
      preLoaderRoute: typeof AnalysisDomainImport
      parentRoute: typeof rootRoute
    }
    '/analysis/page/$pageId': {
      preLoaderRoute: typeof AnalysisPagePageIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AnalysisDomainRoute,
  AnalysisPagePageIdRoute,
])
